### ISSUE TITLE
add faceting specification to Global Discovery Catalogue

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-guide#10]
As mentioned in TT-WISMD 2023-05-05 by Tom GDC should use Facets. 
Faceting offers filter options for search result lists. Due to increasing metadata amount it is important to have additional possibilities to reduce items of a search result list that a user has to pass. Faceting is based on indexed fields as categories and all different values contained in the search result list items are offered as filter options.
Example:
Starting a full text search for "temperature" in our WIS Portal under https://gisc.dwd.de and set facet filter "Originator" (under "Filter by:") to "NC Mali" reduces the result list from 63667 matches to 26.
All indexed fields could be used as facets. 
Different implementations can point out advantages and disadvantages in practice over time, so in my view we should minimize requirements.
In the WCMP2 also for this reason, fixed word lists should be used if possible to avoid spelling variants, typos, different words for the same content, as these lead to different filter options and unnecessarily lengthen the filter option lists

**Comment by tomkralidis** [comment]
I've transferred this to the WIS2 Guide given that this capability is bound to the GDC proper as an API facility.

I'll open a specific WCMP2 issue to identify properties that a GDC should take into account to configure/enable/allow as facets.

**Comment by tomkralidis** [comment]
PR in #25
