### ISSUE TITLE
In the Data Consumer part...

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2-guide#113]
This is the part where the fact that multiple brokers and multiples caches imply that a data consumer has to apply filter so that there is only one download...

This is a copy of text that was in the transition. Jeremy and I agreed that the transition guide for the gateway should mention the data consumer role and not re-explain the how to do it.

. Parse the notification message, discarding it if:
.. The notification message is a duplicate.
.. The notification message refers to data that has already been republished by the Gateway.
.. The notification message does not include the ``gts`` property.
.. The value of the ``cccc`` property is not on the Gateway's publication whitelist.
. If the notification message was not discarded, then:
.. Parse the notification message to extract the **TTAAii** and **CCCC** which identifies the bulletin that the data should be published within.
.. Download the data indicated in the message, using the __canonical__ link if one is specified.
.. Pass the downloaded data file to the Gateway's MSS via the channel configured for the bulletin (**TTAAii**, **CCCC**).

**Comment by 6a6d74** [comment]
Done. See commit in my local fork [here](https://github.com/6a6d74/wis2-guide/commit/7dcab43eecd014dcf749aa18849adc3e33265a65).

Will close this once commit merged into wmo-im/wis2-guide

**Comment by 6a6d74** [comment]
@golfvert - I don't see your comments. Where should I look?

**Comment by golfvert** [comment]
[ https://github.com/6a6d74/wis2-guide/commit/7dcab43eecd014dcf749aa18849adc3e33265a65?diff=split&w=0 | https://github.com/6a6d74/wis2-guide/commit/7dcab43eecd014dcf749aa18849adc3e33265a65?diff=split&w=0 ] 

Here. 
Rémy 

-- 
Rémy Giraud 
Responsable du Département Infrastructure du SI - DSI/ISI/D 
[ https://public.wmo.int/en/governance-reform/infrastructure-commission | Chair of WMO INFCOM SC-IMT ] 
Météo-France, 42 Avenue Coriolis, 31057 Toulouse Cedex, France 
Tél: +33561078173, Mob: +33661667754, Email: ***@***.***

**Comment by 6a6d74** [comment]
Will look at these tomorrow. @tomkralidis - I feel another commit coming; I missed Rémy’s comments so far.

**Comment by tomkralidis** [comment]
ok, holding...

**Comment by 6a6d74** [comment]
Everything fixed; @golfvert has approved. Closing this issue now.
