### ISSUE TITLE
"+" signs don't always render in the documentation

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-guide#114]
Example: `global-services.adoc`

The raw asciidoc is (line 135):

````
* For messages received on topic `+origin/a/+/data/core/#+` or `+cache/a/+/data/core/#+` a Global Cache shall:
````

But the rendered text is:

> For messages received on topic origin/a//data/core/` or `+cache/a//data/core/+ a Global Cache shall:

The wildcard `+` characters are missing after `origin/a/` and `cache/a/`

**Comment by tomkralidis** [comment]
Fixed in #115
