### ISSUE TITLE
review notification inline size over course of pilot

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-guide#13]
In relation to https://github.com/wmo-im/wis2-notification-message/issues/6#issuecomment-1557174736, assess notification message inline content size (proposed 4096 bytes) over course of pilot phase.

**Comment by efucile** [comment]
**Decision**

Keep 4096 bytes as max inline content size.

**Comment by tomkralidis** [comment]
- inline content remains 4096 bytes
- total message size is 8192 bytes
