### ISSUE TITLE
Defining the mime type for WMO formats (GRIB and BUFR)

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-guide#135]
There's variation in how WIS2 Nodes are declaring the mime type for data being shared on WIS2 (e.g., within the link object(s) of WIS2 Notification Messages) .

BUFR files might be given:

`"type": "application/octet-stream"` or `"type": "application/x-bufr"`.

`x-bufr` (and `x-grib`) aren't officially registered mime types, so there's reluctance to use them. `octet-stream` could be any kind of binary format, which isn't helpful for client applications!

We need guidance on what mime type(s) to use.

Would also be good if BUFR and GRIB were properly registered.

I think we have 3 issues to resolve:

- [x] Register BUFR (BUFR4) file format as a mime type with IANA
- [x] Register GRIB (GRIB2) file format as a mime type with IANA
- [ ] Update the WIS2 Guide to say which mime types should be used for the formats commonly used in WIS2

For reference:

- registration process with IANA can be found [here](https://www.iana.org/form/media-types)
- issue on BUFR mime type: [wmo-im/BUFR4#140](https://github.com/wmo-im/BUFR4/issues/140)
- Issue on GRIB mime type: [wmo-im/GRIB2#175](https://github.com/wmo-im/GRIB2/issues/175)

**Comment by golfvert** [comment]
The idea of `x-` is to allow using unregistered names for particular usage.
So, for me using x-bufr and x-grib falls perfectly in this situation.
However, those are standard in quite a large community ans therefore should be registered.
I would therefore do:
- change WIS2 Guide and mandate the use of x-bufr and x-grib for those type of files. If we start doing this, we should also include other cases, waterml, netcdf,... We don't want the WIS2 Guide to be only weather oriented.
- liaise with IANA to register bufr and grib as acceptable names.

When agreed, update the guide.

**Comment by mrauhala** [comment]
Also CAP is now marked application/xml. That should have its own as well. Now type is only way to know what type of data it is (from notification), so it should be as specific as possible, not just application/xml in this case. There is also problem in content property (of notification message), it does have encoding property but not type, so currently there is no way to know that inline content is.

**Comment by golfvert** [comment]
Based on this @amilan17 , can WMO Sec. starts the procedure ?

**Comment by amilan17** [comment]
GRIB and BUFR media types are now included on the IANA site. 
https://www.iana.org/assignments/media-types/media-types.xhtml#application
