### ISSUE TITLE
fix typo in part 2

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-guide#139]
In https://github.com/wmo-im/wis2-guide/blob/main/guide/sections/part2/operations.adoc#interoperability-with-external-systems

`s/priciples/principles/`

In https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_service_levels_performance_indicators_and_fair_usage_policies

`s/availibility/availability/`

NOTE: I am NOT issuing a PR yet until update workflow / branching is confirmed (cc @amilan17)

**Comment by tomkralidis** [comment]
PR in #145

**Comment by amilan17** [comment]
Removed from FT milestone, because this is just an editorial fix that is already addressed in the preparation for LSP.
