### ISSUE TITLE
Amend Guide to reflect updated Global Broker metrics 

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-guide#163]
@golfvert proposes updated metrics for the Global Broker in [wis2-metric-hierarchy/pull/19](https://github.com/wmo-im/wis2-metric-hierarchy/pull/19) - the problem is that Global Brokers are merging into one metric the absence of metadata and an invalid topic used.

The proposed changes are as follows:

1. `wmo_wis2_gb_messages_no_metadata_total` exists as a metric, but it's value is incremented by 1 only if there is no corresponding discovery metadata. Which means that the text in the current Guide [A] would need to be amended to something like:

> A Global Broker will check if a discovery metadata record exists corresponding to the topic on which a message has been published. If there is no corresponding discovery metadata record, the Global Broker will discard non-compliant messages and will raise an alert. The metric `wmo_wis2_gb_messages_no_metadata_total` will be increased by 1. Global Broker should not request GDC for each notification message but should keep a cache of all valid topics for every centre-id.

... The Guide doesn't say how this is validated, but I recall that a GB would maintain a list of topics mentioned in all discovery metadata records, and check that there's a match on that list when validating messages. Does the GB also check that the value of the (optional) `properties.metadata_id` message attribute, if provided, matches the ID of the discovery metadata record that mentions the topic on which the message has been published?

2. `wmo_wis2_gb_invalid_topic_total` is new; a new bullet point should be added to the guide (taking some of the the text in [A]), something like:

> A Global Broker will check if the topic on which the message is received is valid. If the topic is invalid, the Global Broker will discard non-compliant messages and will raise an alert. The metric wmo_wis2_gb_invalid_topic_total will be increased by 1.

3. `wmo_wis2_gb_invalid_format_total` is new; the text mentioned in [B] should be amended, something like (this text includes the change already committed in the GH version with the correct ref to 1060 Vol II Appendix E):

> A Global Broker will validate notification messages against the standard format (see Manual on WIS, Volume II – Appendix E: WIS2 Notification Message), discarding non-compliant messages and raising an alert. The metric `wmo_wis2_gb_invalid_format_total` will be increased by 1.

4. `wmo_wis2_gb_messages_invalid_total` as mentioned in [B] metric is now not used - its function has been split into two separate metrics - see points (2) and (3).

...

The new metrics mentioned in points (2) and (3), and the removal of the metric mentioned in (4) are consistent with the outstanding PR: [wis2-metric-hierarchy/pull/19](https://github.com/wmo-im/wis2-metric-hierarchy/pull/19)
...

[A]:
From [https://library.wmo.int/viewer/68923/download?file=1353_INFCOM-3_en.pdf&type=pdf&navigator=1](https://library.wmo.int/viewer/68923/download?file=1353_INFCOM-3_en.pdf&type=pdf&navigator=1), #2.7.3.1 bullet 8:

> A Global Broker will check if the topic on which the message is received is valid (in particular, a discovery metadata record must exist with a corresponding topic in order that data can be made available using this topic). If the topic is invalid, the Global Broker will discard non-compliant messages and will raise an alert. The metric wmo_wis2_gb_messages_no_metadata_total will be increased by one. Global Broker should not request GDC for each notification message but should keep a cache of all valid topics for every centre-id.

[B]: 
From [https://library.wmo.int/viewer/68923/download?file=1353_INFCOM-3_en.pdf&type=pdf&navigator=1](https://library.wmo.int/viewer/68923/download?file=1353_INFCOM-3_en.pdf&type=pdf&navigator=1), #2.7.3.1 bullet 10:

> A Global Broker will validate notification messages against the standard format (see Notification message format and structure), discarding non-compliant messages and raising an alert. The metric wmo_wis2_gb_messages_invalid_total will be increased by 1.

**Comment by tomkralidis** [comment]
Fixed in #164.
