### ISSUE TITLE
clarify GDC metadata archive zipfile composition

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-guide#171]
Given GDC is required to provide a metadata archive zipfile, provide additional details on the composition of the zipfile.  This was raised during WIS2 Global Services testing in September 2024 where Canada and Germany GDC produced a zipfile with all WCMP2 records at the "root" of the zipfile (when unzipped) and CMA GDC enclosed the same in a directory named after the GDC centre id.

There is value in the CMA GDC approach to be able to "self identify" a given archived when unzipped using a directory:

```bash
|____cn-cma-global-discovery-catalogue
| |____int-eumetsat-serviri-core.json
| |____ca-eccc-msc-gdc.global-discovery-catalogue.json
| |____cn-cma.nmic.prediction-forecast.json
| |____de-dwd.icon-eps-all.json
```

Note that we do not/will not provide any provisions on the filename of each WCMP2 document.

**Comment by amilan17** [comment]
@tomkralidis marked as an revision to the original FT2024-2 amendments based on feedback received during NFP period of review.
