### ISSUE TITLE
Clarify the retention for the WIS2 node

### ISSUE THREAD

**Issue by Haddouch101** [wmo-im/wis2-guide#18]
In GTS the retention is at least 3 months. The WIS2 node is expected to replace the AMSS, we need to clarify the data retention on WIS2 node

**Comment by 6a6d74** [comment]
@Haddouch101 -- Please can you indicate the clause in WMO Tech Regs that says data must be retained for 3-months on GTS.

I don't disagree with the logic -- but if there's no existing Tech Reg, we'll need INFCOM approval (maybe EC approval) because it will have financial implications on Members.

**Comment by 6a6d74** [comment]
@Haddouch101  - update please.
