### ISSUE TITLE
KPIs for transition from GTS to WIS2

### ISSUE THREAD

**Issue by Haddouch101** [wmo-im/wis2-guide#20]
to update the guide to WIS

**Comment by 6a6d74** [comment]
Needed for the Guide ... but we determine how we measure the transition to make sure we can drive the right behaviour. Sooner we understand the KPIs the sooner we can start communicating this to Members.

**Comment by 6a6d74** [comment]
Examples:

- Migration statistics (number of Members on WIS2, number of WIS2 Nodes, number of GTS message switches decommissioned, number of lines of the routing table deleted etc.)
- Statistics on new data products made available on WIS2 (that weren't on GTS)
- ?

**Comment by antje-s** [comment]
perhaps also a metric for 
- number of GTS-messages available in WIS2 only under GTStoWIS2-Gateway topic (and not in the "normal" WIS2 topic subtree)
- number of countries disseminating observation data in GTS but not (yet) in WIS2

**Comment by kaiwirt** [comment]
So far, TT-WISMON provides software (https://github.com/wmo-im/monitoring) which outputs metrics for data received on two different data streams (one can be GTS, one can be WIS2). 
GISC Offenbach provides the metrics for our GTS/WIS2 reception at https://opendata.dwd.de/test/wis2/cache/metrics/globalcache/gc_metrics.txt with prefix wmo_wis2_sensor on a per station and per country basis.

One issue so far is, that some stations report using WMO station numbers in GTS and with WSI in WIS2.
