### ISSUE TITLE
Guidance for data consumers

### ISSUE THREAD

**Issue by Haddouch101** [wmo-im/wis2-guide#22]
Guidance for data consumers subscribing to notifications from Global Broker; managing duplicates vs. managing failover; use of replay service; etc.

**Comment by 6a6d74** [comment]
ECWMF and others have thought about this problem for their data publication. They've spent a lot of time writing documentation, code snippets, software libraries, [python] notebooks etc. that show users how to do stuff.

[ECMWF open data](https://github.com/ecmwf/ecmwf-opendata/blob/main/README.md)
... and the [collection of python notebooks and code snippets](https://github.com/ecmwf/notebook-examples/tree/master/opencharts)

**Comment by 6a6d74** [comment]
Guidance added. See PR #116
