### ISSUE TITLE
Simple NC/DCPC data sharing in data-and-metadata-flows.adoc

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/wis2-guide#29]
In my understanding the simple NC/DCPC data sharing described in data-and-metadata-flows.adoc is not part of WIS2 and should be removed. Also WIS2 Nodes are not required to operate a local metadata catalogue. 

If this section is intended to illustrate the concept this should be made clear explicitly.

**Comment by 6a6d74** [comment]
Discussed at ET-W2AT, 16-Oct-2023.

### Discussion

The _Data and Metadata Flows_ section is very detailed - useful for implementors, not for users. The Guide is intended for Users - data consumers, data publishers, global service operators.

We agree that the _Simple NC/DCPC Data Sharing_ is not valid and should be removed in its current form. The intent was to introduce people to the concept of publishing notification messages and using the info therein to determine whether to download a given resource. 

@golfvert showed a sequence diagram showing interactions between components. We agreed that this was the appropriate level of detail.

The detailed "technical blueprints" are useful and should be published somewhere. 

### Recommendation

Section 4 of the [Data and Metadata Flows](https://wmo-im.github.io/wis2-guide/guide/wis2-guide-DRAFT.html#_data_and_metadata_flows_in_wis2) will be removed from the Guide and published as an external resource. The _Simple NC/DCPC Data Sharing_ subsection should be re-written to introduce people to the concept of publishing notification messages and using the info therein to determine whether to download a given resource.

This external resource will be published in a "reference library"; e.g., _WIS2 architecture and development_ - name/place to be determined. These external resources will not need approval by INFCOM.

The Guide should have a short (i.e., 2-paragraph) section on WIS2 Architecture, with reference to more detailed technical resources.

### Actions

Update the Guide

Validate whether Mermaid (text-driven sequence diagram generator) is compatible with ASCII Doc publication << @golfvert, @tomkralidis  

Establish a reference library for WIS2 technical resources << @efucile

**Comment by tomkralidis** [comment]
updates:
- a WIS2 Architecture Guide document is now availble at https://github.com/wmo-im/wis2-architecture-guide
  - @tomkralidis to bootstrap
- Mermaid can be used in AsciiDoc/Asciidoctor ([main documentation](https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/mermaid/)).  [Installation](https://docs.asciidoctor.org/diagram-extension/latest/installation/) and [rendering](https://docs.asciidoctor.org/diagram-extension/latest/generate/) steps are documented accordingly

For WIS2 Guides, this would be added to an AsciiDoc as follows:

```adoc
[mermaid]
----
sequenceDiagram
    title: Adding a new WIS2 Node
    GlobalCaches->>GlobalBrokers: Subscribe to origin/a/wis2/#
    Center->>WMO: My organisation is ready to run a WIS2 Node.
    Note over WMO,Center: Center has been already approved by PR.
    WMO->>Center: OK. What would be the centre_id ? 
    Note over WMO,Center: The centre_id should be based<br/>on the name of your organisation.<br/>Typically, the domain name is a good choice.<br/>Then, if you intend to run multiple WIS2 Node, each one<br/>must have its own centre_id. The ISO3166 2-lettre code for<br/>your country is ab.
    Center->>WMO: I propose "ab-myorg-climate"
    Note over WMO,Center: My main website can be reached at https://www.myorg.ab<br/>This WIS2 Node will provide climate data.
    WMO->>Center: Can you give me the information of your broker endpoint ?
    Center->>WMO: Here they are.
    Note right of Center: Such information includes the protocols<br/> preferably a secure version so MQTTS,<br/>using a valid certificate, a username<br/>and a password, and the topic(s) to subscribe to.
    Note right of WMO: All information is recorded<br/>in the WIS2 Node database
    WMO->>Center: That is fine. Let me contact the GISC for your country.
    Create participant GISC
    WMO->>GISC: Center is ready with WIS2 Node ab-myorg-climate.<br/>Can you check if everything is correct ?
    GISC->>Center: Can we check your WIS2 Node implementation ? 
    Note left of GISC: GISC must verify that Center<br/>as implemented a WIS2 compliant solution.
    GISC->>Center: Can you publish some test messages with the associated files to download ?
    Note left of GISC: By using a test MQTT client, the GISC can<br/> verify that the Notification Message is correct<br/>and that the download links are working.
    Center->>GISC: Done. 
    GISC->>Center: The MQTTS connection is working. The notification message is correct. The download link works. All good!
    Note left of GISC: The GISC verifies that the topic used by the center<br/>is compliant with the agreed topic hierarchy.<br/> Compliance of the Notification Message<br/>with the specifications is also verified.<br/>The download link is using HTTPS which is prefered.
    GISC->>Center: When your dataset is ready, please ensure to provide the relevant metadata record!
    GISC->>WMO: All checks are good. This new centre_id can be added to WIS2.
    WMO->>GlobalBrokers: A new centre_id is available. Can you subscribe to the broker endpoint? Here are the details.
    GlobalBrokers->>Center: Subscribe to agreed topic(s) 
    GlobalCaches->>Center: Download and cache metadata records.<br/> Download and cache core data (if applicable).
----
```

We will have to test some output (sizing, legibility).
