### ISSUE TITLE
add GDC validation of WCMP2 id against incoming topic

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-guide#35]
Given data providers publish discovery metadata to the `.../metadata` topic, a GDC SHALL validate the WCMP2 against the topic to which it was published.

cc @amienshxq

**Comment by golfvert** [comment]
To be included in the Guide.

**Comment by tomkralidis** [comment]
Example:

- centre-id ca-eccc-msc publishes WCMP2 document to topic `origin/a/wis2/ca-eccc-msc/metadata`
- WCMP2 document has an identifier of `urn:x-wmo:md:fr-meteo-france:observations.swob`

The GDC should check for a match and raise an error/report if there is no match.

Action: @tomkralidis to add to Guide under GDC.

**Comment by 6a6d74** [comment]
Tom to update the Guide :)

**Comment by tomkralidis** [comment]
PR in #80
