### ISSUE TITLE
specify guide for report format

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-guide#44]
WIS2 users are able to publish notifications data, metadata and reports.  An example of a report notification:

- `origin/a/wis2/can/eccc-msc/report`

Examples:
- GDC publishing the availability of the metadata archive (per https://github.com/wmo-im/wis2-guide/issues/9#issuecomment-1764918318)
- Global Services providing notifications about metrics in support of Global Monitoring
- other examples?

Areas for clarification:
- when a message is published to this topic, should the payload be WNM, or allow / extend?
- if WNM, then we determine guidance in the WNM issue tracker proper
- if not WNM, provide direct guidance in the guide

**Comment by 6a6d74** [comment]
Closing this. Superseded by conversations about how we'll do monitoring.
