### ISSUE TITLE
Add examples to WIS2 Guide indicating how attribution / other license should be expressed in the WIS2 Discovery Metadata

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-guide#47]
In support of Data Policy implementation, SC-IMT has tasks relating to attribution of data:

1. Encourage honouring of attribution [for Core data] (data policy implementation task 5)
2. Urge transparent conditions for use of recommended data (data policy implementation task 7)
3. Urge respect of conditions for use of recommended data (data policy implementation task 8)

The WIS2 Guide seems like the right place to include good practice on these tasks - both in terms of how the attribution clause / license are expressed in discovery metadata, and reminding (?) users of their obligations wrt conditions of use (e.g., showing how to cite WMO data).

**Comment by tomkralidis** [comment]
W2AT 2023-11-14

WCMP2 examples: https://wmo-im.github.io/wcmp2/standard/wcmp2-DRAFT.html#_properties_wmo_data_policy

- WMO to create text for core data attribution and publish to a URL
- WCMP2 will provide a recommendation to add as a link with `rel=license`
