### ISSUE TITLE
Access control of recommended data

### ISSUE THREAD

**Issue by efucile** [wmo-im/wis2-guide#50]
A data provider can implement access control for recommended data. Do we have a requirement to allow only a limited number of mechanisms to simplify the task of a user who needs to subscribe to different streams of recommended data?

**Comment by efucile** [comment]
This is a comment from @tomkralidis 

Note that in WCMP2 we support describing security in the context of a link having an optional security object based on the [OpenAPI security schemes](https://github.com/OAI/OpenAPI-Specification/blob/3.1.0/schemas/v3.0/schema.yaml#L754-L759).

**Comment by 6a6d74** [comment]
- [ ] @6a6d74 to update Guide (Data Publisher section, 2.6.3) to tell data publishers what they need to do
- [ ] @tomkralidis to update WNM spec to reference inclusion of a security object - mirroring what's already written in WCMP2.

**Comment by 6a6d74** [comment]
[New issue created for update to WNM spec](https://github.com/wmo-im/wis2-notification-message/issues/90#issue-2101448338):

**Comment by 6a6d74** [comment]
Done. New section for Data Publishers: Implementing access control.
