### ISSUE TITLE
approval of centre-id between fast-track cycles

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-guide#51]
Once WIS2 enters the operational phase in 2025, the WIS2 Topic Hierarchy will be managed via the WMO Fast Track process.

At the November W2AT face-to-face meetings, an `experimental` level was added for all domains to use for provisional domain topics in support of publishing data between FT cycles.

While this provides utility for new domain topics between FT cycles, we need to consider how to register new `centre-id`'s as well (which are managed at a higher level [without an experimental option]).

cc @golfvert @6a6d74 @efucile

**Comment by golfvert** [comment]
Once the Centre as been validated by the PR (or equivalent), agreeing on the centre-id is a bilateral action between WMO and Centre. There is no need for higher level endorsement.
Shall we create a metadata to describe the centre-id and its goal. WMO could do it and it would be stored in GDC as another metadata. Doable ?

**Comment by tomkralidis** [comment]
Related: https://github.com/wmo-im/wis2-topic-hierarchy/issues/21

**Comment by tomkralidis** [comment]
PR in https://github.com/wmo-im/wis2-topic-hierarchy/pull/78
