### ISSUE TITLE
Global Cache behaviour for recommended data

### ISSUE THREAD

**Issue by kaiwirt** [wmo-im/wis2-guide#65]
ET-W2AT 08.01.2024: Global Caches do only care about core data and do not subscribe to or republish WNM for recommended data. There might be two issues associated with this when data users subscribe to origin/a/wis2/#

* Download requests directly to WIS2 nodes which can not offer enough bandwidth. This might also impact the performance of Global Caches when accessing these WIS2 nodes
* Bad user experience if WIS2 nodes limit access to their http endpoints for core data to Global Services (failed downloads).

In the pre-operational phase we need to check if this behaviour is an issue.

**Comment by kaiwirt** [comment]
> @6a6d74 Summary of discussion from Jan 8th:
 * expects notification messages about recommended data to be at least as numerous as those for core data - getting the Global Caches to process all those extra messages for zero functional value seems wasteful
 * Data Consumers may accidentally (i.e., cut and paste) or deliberately (i.e., because messages arrive a fraction quicker) subscribe to origin/a/wis2/{centre-id}/data/core/* instead of cache/a/wis2/{centre-id}/data/core/*
* We note that it may be useful for Data Consumers to see origin vs. cache (and core vs recommended) to signal (potential) differences in usage conditions for data.
 * Main problem with subscribing to origin/a/wis2/{centre-id}/data/core/* is that the URLs in notification messages published to that topic will point to the WIS2 Node (not the Global Cache) - and we don't want people to download from origin!
* For now we'll assume that Data Consumers behave properly :) - GCs will ignore notification messages for "recommended data" (Guide to be updated by @kaiwirt)
* New Issue to be created by @kaiwirt describing the potential that data consumers may start subscribing to origin/a/wis2/{centre-id}/data/core/* instead of the cache branch of the topic hierarchy 
* We'll review what happens in practice (i.e., which topics people subscribe to / where people download from) and take remedial action - assessment pending mid-2024.

**Comment by kaiwirt** [comment]
> @golfvert To prevent that, we can use authorization in MQTT. The everyone/everyone would NOT have access to origin...core and only to cache...core and origin...recommended. Then the Global Services would not use everyone/everyone. Which would be a good thing any way. Typically, if we want to used shared subscription (for Global Cache that would be very useful), then, each Global Service would need it's own user/pwd.

**Comment by 6a6d74** [comment]
Complete. See PR #85
