### ISSUE TITLE
In the Manual we say at the beginning of Vol. 2 that for WIS we mean WIS 2.0. We should do the same in (the introduction section of?) the Guide.

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-guide#68]

**Comment by 6a6d74** [comment]
@efucile / @hhaddouch - for action.

**Comment by tomkralidis** [comment]
Simple but important issue.  Further questions:

- should/do we name everything "WIS" and jettison "WIS 2.0", "WIS2", "WIS 2", etc.?
- if yes, do we put "WIS means WIS 2.0" in the introduction

What we decide here should also cascade into the Manual, Transition Guide,  WCMP2, WNM, and WTH.

**Comment by tomkralidis** [comment]
Superseded by #76
