### ISSUE TITLE
Prevent caching of large datasets in Global Caches

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2-guide#7]
Centres like ECMWF or Eumetsat will provide very large amount of core data that nevertheless should not (or may not) be stored in the Global Cache.
In the current approach, there is no mechanism to prevent those kind of data not to end up in the cache.
Right now all data published using messages in the topics `origin/a/wis2/country/centre-id/core/# ` will end up being caught by Global Cache and copied.
We should define a way to prevent that default behaviour.

_updated: 31 May 2023_

===DECISIONS
1. for core data, add properties.cache (true|false, default=true) to the notification message as decided by data producer
1. if properties.cache: false the Global Cache SHALL:
     * Not download the data made available using this message
     * Publish the Notification in cache/a/wis2/... (similarly to the data being cache) with the properties.links not modified (the link will still point to the data producer endpoint)

**Comment by golfvert** [comment]
Some possible options to consider:

1. Adding in the notification message a `cache: false` in the properties
2. Having this "no cache" as part of the metadata description
3. Having those datasets directly published in the `cache/a/wis2/...` topic tree and having the handful Global Caches to use a list of not to be cached topic hierarchy. Typically those published by ECMWF, Eumetsat and a few (?) others.
4. Else ?

**Comment by kaiwirt** [comment]
Caches might want to use the length field in the message to decide whether they will be able to handle that data volume. If that field is missing they could still decide if they are going to store the data to the cache after the download finished.

**Comment by efucile** [comment]
I vote for option 3

**Comment by 6a6d74** [comment]
Before looking for the right mechanism, I think it makes sense to agree _who_ decides if things are cached.

Is it the data publisher? In which case putting a flag in the discovery metadata or notification message would work.

Is the cache operator? In which case "message length" could be a useful criteria. 
... Aside: given that all caches would produce their own notification messages, would WIS2 work if caches made different decisions about what they were willing to cache. Example: if only Germany cached some things, consumers would only receive notifications pointing to the German cache?

The data publisher probably has a better idea of whether the data is real-time or near-real-time.
Aside: maybe the update frequency (specified in the discovery metadata) is a good metric for identifying real-time or near-real-time data?

The cache owner is the one impacted by the choice in terms of data down/upload and storage cost.

**Comment by golfvert** [comment]
And to have the complete picture to consider as well the impact for users.

**Comment by tomkralidis** [comment]
It also depends on whether limits will be mandated across all global services, or vary across same.  In either case:

- putting `cache: bool` (default: `true`) in discovery metadata would mean other global services supporting a lookup between discovery metadata and data notifications.  We recently added an (optional) `properties.metadata_id` element to the notification message which could facilitate this, but again it is optional
- putting `cache: bool` (default: `true`) in the notification message would allow the data publisher to specify caching at a data granule ("*from this collection, cache this file, but not that one*")
- putting `cache: bool` (default: `true`) may be valuable for articulating that a data granule should not be cached for a other reason than size
- using the message `properties.content.size` value, or a link object's `length` value can help provide an indication to Global Services to decided accordingly.  If limits are Global Service specific, then the Global Service should communicate this constraint somehow (an AsyncAPI definition for GB, or a landing page for GC).

**Comment by golfvert** [comment]
The `cache: bool` in the notification message is probably the easiest to manage for WIS2 Nodes and Global Cache operations.
This can added in the Metadata record so that this information is known upon discovery of the data.

From a user perspective, however, this may imply that he would have to subscribe to origin/a/wis2/... for receiving the non cached data.
Which is not very convenient IMHO.

An alternative to my option 3. above is for the WIS2 Node to:
- add `cache: false` in the message 
- post this on origin/a/wis2/... as usual
and for the Global Cache:
- not to download/cache the data with `cache: false`
- nevertheless republish the message onto cache/a/wis2/... without updating the download link(s).

This way, as a user, I don't really care I subscribe to cache/a/wis2/... and I will receive the correct links in the message.

Like that, WIS2 Node is in control, Global Cache follow a simple rule, user doesn't require to know about this subtlety.

**Comment by 6a6d74** [comment]
That's a neat solution. It means that data consumer wanting core data doesn't have to worry about whether it's on `cache` or `origin` topics at the Global Broker. Notifications about core data will _always_ be available via the `cache/a/wis2` topics.

We just need to clearly document the (counter intuitive) situation of when a `cache/a/wis2` topic message doesn't point to a URL at a Global Cache. From inspecting a notification message it will be obvious - because it must include a "don't cache me" `cache: false` directive.

It also means that the Global Discovery Catalogue can treat _all_ core data the same - adding an additional actionable link pointing to subscription via the `cache` topic. So there's no need for the WIS2node to include a special cache me / don't cache me directive in the metadata.

BTW - I'm assuming that the Global Discovery Catalogue adds an actionable link for the associated `cache/a/wis2/...` topic at _every_ Global Broker? This is the way that data consumers find out where they can subscribe - I'm expecting this to be a list of places, one or more of which is relevant for them.

**Comment by golfvert** [comment]
"We just need to clearly document the (counter intuitive) situation..." does it _really_ matter?
As a user, I receive a message, I follow the link(s) and done. 
We can mention that in the guide, as the download links may not be limited to `dwd.de` or... for core and recommended that's all.

**Comment by golfvert** [comment]
@kaiwirt, is this potential solution (don't cache but re-publish me) a good option for you as a Global Cache centre?

**Comment by 6a6d74** [comment]
> "We just need to clearly document the (counter intuitive) situation..." does it _really_ matter? As a user, I receive a message, I follow the link(s) and done. We can mention that in the guide, as the download links may not be limited to `dwd.de` or... for core and recommended that's all.

@golfvert - by documentation yes, I meant mention it in the guide - I'm sure that some Global Cache implementers might not get the point unless we're explicit with the reason.

**Comment by kaiwirt** [comment]
To me i think it is ok if caches republish messages without actually downloading and storing the data leaving the message unmodified but the topic.

Caches could also indicate this in the message. Having a flag like on_local_cache: true/false

**Comment by antje-s** [comment]
Sounds good, I just have one addition...
from my point of view it would be important for the automatic download of core data that the access to origin-download-URLs is open (without login for all WIS2 Nodes) otherwise the list of access data can become very long.

**Comment by golfvert** [comment]
As ECMWF will have its WIS2 Node soonish, and its data shouldn't be cached, shall we tentatively endorse:

1. WIS2 Node can add `cache: false` in the Notification message. Default value being `cache: true` (if `cache` key is missing)
2. Global Cache honours `cache: false` by NOT downloading the data and, nevertheless, publishes on the corresponding  `cache/a/wis2/...`

If that is acceptable, then @tomkralidis can amend the WIS2-notification-message repo accordingly.

**Comment by kaiwirt** [comment]
Hi Remy,

we can add this feature. No objections.

If we agree on this procedure we should in the same line agree what to do with recommended messages. In that case I would prefer having the same logic such that a Global Cache is not downloading recommended data, but is republishing the message at cache/a/wis2


Best regards


Kai

-----Ursprüngliche Nachricht-----
Von: Remy Giraud ***@***.***> 
Gesendet: Montag, 20. März 2023 10:57
An: wmo-im/wis2-guide ***@***.***>
Cc: Wirt Kai-Thorsten ***@***.***>; Mention ***@***.***>
Betreff: Re: [wmo-im/wis2-guide] Prevent caching of large datasets in Global Caches (Issue #7)

As ECMWF will have its WIS2 Node soonish, and its data shouldn't be cached, shall we tentatively endorse:

1.	WIS2 Node can add cache: false in the Notification message. Default value being cache: true (if cache key is missing)
2.	Global Cache honours cache: false by NOT downloading the data and, nevertheless, publishes on the corresponding cache/a/wis2/...

If that is acceptable, then @tomkralidis <https://ofcsg2dvf1.dwd.de/fmlurlsvc/?fewReq=:B:JV07MDQ1Oyd3PDMvMSdoZTwxMDsxMCdyaGZvYHV0c2Q8ZWdkYjk3Y2Q5OGM1ZGMwM2c5NTM4ZzgyZzExYzU2YjRnYDI4ZTY5MSd1PDA3NjgyMTczNTcncGhlPDIzSjh3UGAwMTIzNzUzLDIzSjh3UGAzMTIzNzUzJ3NicXU8SmBoLFVpbnNydWRvL1Zoc3VBZXZlL2VkJ2I8NDMnaWVtPDE=&url=https%3a%2f%2fgithub.com%2ftomkralidis>  can amend the WIS2-notification-message repo accordingly.

**Comment by tomkralidis** [comment]
TT-WISMD 2023-04-12:
- potentially distributes responsibility?
- global services can/should decide
- can have both
 - data producer driven (in WNM)
 - decision by global services
   - can notify data producer that data was not cached
     - traffic/load?  Can send single message (report) to global service
   - data producer can also subscribe to global broker to validate their data publication
- global service should be able to govern if a data granule gets cached or not

Recommendation:
- can have both, global cache can override
- global cache can realize as an implementation detail
- global service SHALL have a WCMP2 record (`properties.type="service"`)
  - rules can be communicated in themes/concepts?
  - constraints

**Comment by golfvert** [comment]
A small complement to the summary above:

- for core data, add properties.cache (true|false, default=true) to the notification message as decided by data producer
- if `properties.cache: false` the Global Cache SHALL:

1. Not download the data publish using this message
2. Publish the Notification in `cache/a/wis2/...` (similarly to the data being cache) with the `properties.links` not modified (the link will still point to the data producer endpoint)

2. is to make users' life easier. They will keep subscribing to the topic `cache/a/wis2/...` only. The "no cache core data" being a technicality, there is no need to expose this to user.

**Comment by tomkralidis** [comment]
Associated PR in https://github.com/wmo-im/wis2-notification-message/pull/46

**Comment by kaiwirt** [comment]
Just for my clarification. We use the same mechanism for recommended data: GC receives message on origin/#, it does not download the data but republishes the (unmodified) message as cache/#

**Comment by SimonElliottEUM** [comment]
> Before looking for the right mechanism, I think it makes sense to agree _who_ decides if things are cached.
> 
> Is it the data publisher? In which case putting a flag in the discovery metadata or notification message would work.
> 
> Is the cache operator? In which case "message length" could be a useful criteria. ... Aside: given that all caches would produce their own notification messages, would WIS2 work if caches made different decisions about what they were willing to cache. Example: if only Germany cached some things, consumers would only receive notifications pointing to the German cache?
> 
> The data publisher probably has a better idea of whether the data is real-time or near-real-time. Aside: maybe the update frequency (specified in the discovery metadata) is a good metric for identifying real-time or near-real-time data?
> 
> The cache owner is the one impacted by the choice in terms of data down/upload and storage cost.

A producer of core data needs to know in advance whether they will be cached or not. If core data are not cached than the producer will have to accommodate data access from an unknown number of consumers, as opposed to one download from the global cache. The caching of the core data at the Global Caches is a key advantage of the WIS2 architecture from the point of view of a producer of large volumes of such data.

**Comment by efucile** [comment]
Decision

An increase in the volume of data has to be announced by the provider in advance to allow the GCs to take required measures.

===DECISIONS

for core data, add properties.cache (true|false, default=true) to the notification message as decided by data producer
if properties.cache: false the Global Cache SHALL:
Not download the data made available using this message
Publish the Notification in cache/a/wis2/... (similarly to the data being cache) with the properties.links not modified (the link will still point to the data producer endpoint)

**Comment by 6a6d74** [comment]
Guide section for Global Cache operators is updated. Need to put appropriate text in section for data publishers (section 2.6.3)

**Comment by 6a6d74** [comment]
Done.  New section for Data Publishers includes this information: "Considerations when providing Core data in WIS2"
