### ISSUE TITLE
add clarification on broker auth and everyone:everyone provision

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-guide#74]
Apparently some deployments will not take `everyone:everyone` as username/password auth (credential too simple).

We have `everyone:everyone` as a convention; we need to clarify this in the Guide given the above reality.

cc @golfvert @6a6d74

**Comment by tomkralidis** [comment]
- WIS2 Nodes need to choose credentials as required.  Default is assumed to be `everyone:everyone`.  Credentials are not managed with confidentiality by WMO Secretariat
- GBs need to provide open access with username and password `everyone:everyone`

@6a6d74 @golfvert

**Comment by 6a6d74** [comment]
Guide is updated.
